import "./globals.scss";
import { Bebas_Neue, DM_Mono } from 'next/font/google';
import { ShoppingBagProvider } from '@/app/components/shopping_bag_context';

const bebasNeue = Bebas_Neue({
  subsets: ['latin'],
  weight: ["400"],
  display: 'swap',
});

const dmMono = DM_Mono({
  subsets: ['latin'],
  weight: ["300"],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${bebasNeue.className} ${dmMono.className}`} >
        <ShoppingBagProvider>
          {children}
        </ShoppingBagProvider>
      </body>
    </html>
  );
}
