import "./globals.scss";
import { Bebas_Neue, DM_Mono } from 'next/font/google';
 

 
const bebas_Neue = Bebas_Neue({
  subsets: ['latin'],
  weight: ["400"],
  display: 'swap',
});

const dm_Mono = DM_Mono({
  subsets: ['latin'],
  weight: ["300"],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` ${bebas_Neue.className} ${dm_Mono.className}`}>
      <body >{children}</body>
    </html>
  );
}

